export const PATH = {
  USERS: "/users",
  PRODUCTS: "/products",
  INVENTORIES: "/inventories",
  TRANSACTIONS: "/transactions",
  LOGIN: "/login",
  LOGOUT: "/logout",
  DELETED: "/deleted",
  ID: "/:id",
  EDIT: "/edit/:id",
  DELETE: "/delete/:id",
  RESTORE: "/restore/:id",
  FORCE_DELETE: "/forceDelete/:id",
  CHANGE_PASSWORD: "/changePassword/:id",
  FORGOT_PASSWORD: "/emailOTP",
  RESET_PASSWORD: "/resetPassword",
};
